# docker-compose.yaml
version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=currency_db
      - EMAIL_SENDER=your@email.com
      - EMAIL_PASS=your_email_password
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=currency_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: